### ISSUE TITLE
Implement tool bar

### ISSUE THREAD

**Issue by Dhsieh** [Dhsieh/ScavengerHuntApp#15]
ActionBarActivity has been deprecated, so it can no longer be used, find a new way to implement the tool bar. If it requires of changing the extended class for MainPage then implement setting the ListView which is currently being set by setListAdapter() which comes from ListActivity.

**Comment by joeyschen** [comment]
Implemented/Changed to AppCompatActivity instead

**Comment by Dhsieh** [comment]
Create a pull request.
